version: "3"
services:
  mongodb:
    image: mongo:3.6.18
    container_name: "mongodb"
    ports:
    - 27017:27017


  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    depends_on:
    - mongodb